%% 职责1+2+3 合并 Prompt：给定统计，产出启发式 + 算子计划 + 局搜提示
function [user_p, schema] = prompt_knowledge(prob, stats)
    % stats: makespan, loadVec, maxLoadMach, stagnation, gen
    % 阶段2：移除 criticalMach 近似字段（真实关键机器由 critical_path 在
    % llm_guided_local_search 中反推）；此处仅用 maxLoadMach 描述负载热点。
    schema = ['{"heuristics":"<一句话调度规则，如优先把长工序排到负荷最低机器>",' ...
              '"levy_gain":<0.5~2.0，Levy 步长增益，>1 加强全局探索>,', ...
              '"diff_gain":<0.5~2.0，水/动物传播强度增益，>1 加强信息交换>,', ...
              '"explore_bias":<0.5~2.0，风传播幅度增益>,', ...
              '"ls_mode":"CRITICAL_BLOCK|MACHINE_REASSIGN|NONE",' ...
              '"target_machine":<整数机器号，或 -1 表示自动>}'];
    user_p = sprintf(['【FJSP 实例】%d 工件 x %d 机器，总工序 %d。\n' ...
        '【进化统计】第 %d 代；当前最优 makespan=%.1f；机器负荷向量=%s；' ...
        '最高负荷机器=M%d（负荷热点，建议优先在此机做机器重指派局部搜索）；' ...
        '近 %d 代改进幅度=%.3f。\n' ...
        '【任务】请输出 JSON 调度知识契约：\n%s\n' ...
        '说明：heuristics 为调度语义规则（仅作记录与可解释性展示，不影响解码/初始化）；' ...
        'levy_gain/diff_gain/explore_bias 为三个 0.5~2.0 的增益系数，' ...
        '分别调制 AOO 的 Lévy 开发步长、传播强度、风传播幅度；' ...
        'ls_mode/target_machine 指导关键块局部搜索。不要修改 AOO 算法本身。'], ...
        prob.nJob, prob.nMachine, prob.nOp, stats.gen, stats.makespan, ...
        mat2str(stats.loadVec,1), stats.maxLoadMach, ...
        stats.stagWindow, stats.stagnation, schema);
end
