%% 职责4 Prompt：种群状态诊断（低频）
function [user_p, schema] = prompt_diagnosis(stats)
    schema = ['{"stagnant":true|false,' ...
              '"diversity":"LOW|MED|HIGH",' ...
              '"action":"INCREASE_EXPLORE|KEEP|INCREASE_EXPLOIT"}'];
    user_p = sprintf(['【进化诊断】第 %d 代；最优=%.4f；均值=%.4f；多样性=%.4f；' ...
        '近 %d 代最优改进=%.5f；是否触发早停阈值附近=%s。\n' ...
        '【任务】输出 JSON 诊断：%s'], ...
        stats.gen, stats.best, stats.mean, stats.diversity, ...
        stats.stagWindow, stats.stagnation, ...
        logical_to_str(stats.nearEarlyStop), schema);
end
